### ISSUE TITLE
WSOD with PHP below 7.3

### ISSUE THREAD

**Issue by xxsimoxx** [ClassicPress/classicpress-seo#162]
`PHP Fatal error: Uncaught TypeError: Return value of Composer\Autoload\ClassLoader::initializeIncludeClosure() must be an instance of Composer\Autoload\void, none returned in .../ClassicPress/src/wp-content/plugins/classicpress-seo/vendor/composer/ClassLoader.php:580`

```
Stack trace:
#0 .../ClassicPress/src/wp-content/plugins/classicpress-seo/vendor/composer/ClassLoader.php(112): Composer\Autoload\ClassLoader::initializeIncludeClosure()
#1 .../ClassicPress/src/wp-content/plugins/classicpress-seo/vendor/composer/autoload_real.php(28): Composer\Autoload\ClassLoader->__construct('/Users/simo/Sit...')
#2 .../ClassicPress/src/wp-content/plugins/classicpress-seo/vendor/autoload.php(25): ComposerAutoloaderInit531772699595bd84a6a8fd835c733f0b::getLoader()
#3 .../ClassicPress/src/wp-content/plugins/classicpress-seo/classicpress-seo.php(266): include('/Users/simo/Sit...')
#4 .../ClassicPress/src/wp-content/plugins/classicpress-seo/classicpress-seo.php(183): in .../ClassicPress/src/wp-content/plugins/classicpress-seo/vendor/composer/ClassLoader.php on line 580
```

Can't find Composer requiring a PHP version > 7.0.

## Possible solutions:
- Fix the issue
- Bump required PHP to 7.4 for version 2.2.0 (breaking SemVer)
- Bump required PHP to 7.4 and release 3.0.0

**Comment by xxsimoxx** [comment]
Bumbing PHP requirements to 7.4 in 2.2.0.
